
[Spawning]
	#This controls whether all boss versions will require specific weather conditions to spawn. Without this, they will appear much more frequently. 
	"Bosses require weather?" = true
	#Do you want the boss and clone versions to spawn naturally, or only from summoning structures?
	"Boss natural spawning" = true
	#Bosses and variant spawns are rare by default. 1=twice as common. 2=default rarity. 3=twice as rare. 4=three times rarer. Avoid decimal and negative numbers.
	"Boss rarity" = 2.0
	#This controls whether the stalker bosses (spider moth, scorpioid bloodluster, draconic voidlasher, tormentor) are included in general. Set to false if you only want the other mobs, and the bosses will become unable to be spawned in any way.
	"Boss inclusion" = true
	#Controls the vanilla biome-specific spawnrates of ALL non-boss mobs in this mod, including minibosses and all regular arthropods. Default multiplier value is 5. You could more than double the ArPhEx spawnrates by setting it to 2 or 1. Lower values = more spawns (minimum value is 1). No maximum rarity. Avoid decimal and negative numbers.
	"Non-boss global spawnrates (biome-specific)" = 5.0
	#ArPhEx has an additional spawning system that gives a 1 in (10) chance to spawn a random ArPhEx mob each time the natural spawn triggers. This system allows ArPhEx mobs to spawn in any non-vanilla overworld biomes, while still accounting for mob rarity. Default number is 5, meaning it has a 1 in 10 chance to spawn each time. Setting it to 0 disables the additional spawning system entirely. Avoid decimal and negative numbers.
	"Random-system spawnrates (not biome-specific)" = 5.0
	#This value controls whether ArPhEx entities are included in general. Setting to false makes it impossible to spawn ArPhEx mobs, while keeping the items as usual. 
	"All entities enabled/disabled" = true
	#Maximum colony tamed ants per player (furthest ants despawn, 20 default)
	"Max tamed ants per player" = 20.0
	#Option to limit all natural ArPhEx spawning to the Crawling dimension. Note that you won't be able to craft a crawling compass, so a mod like traveller's compass is recommended
	"Crawling-restrict all mobs" = false
	#Specifically disables the Tormentor boss entirely. It will be unable to be spawned in any form if this is enabled.
	"Disable Tormentor" = false
	#Disabled by default. If enabled, most mobs will become able to spawn in any dimension, including dimensions from other mods - may cause issues with some mod dimensions. Note, however, that the mobs will have a low spawn weight in other dimensions.
	"Spawn in other dimensions" = false
	#By default, the Tormentor can spawn naturally once you defeat the first three bosses. At this point, you probably won't be ready yet to fight it, and so will be forced to seal it and locate a crawling portal (all intentional). Set to false to prevent this, and ensure the Tormentor can only spawn from being summoned. The earlier - Boss natural spawning - config option has the same effect, but also controls other bosses.
	"Tormentor initial natural spawning" = true
	#Do you want to massively amplify all ArPhEx spawns futher on top of the existing spawns? Enabling this will drastically amplfy random-system overworld spawns from the mod, and even add crawling dimension mobs like the spider ambusher into the overworld. Even the non-overworld bosses will spawn rarely in the overworld, except for the Tormentor (this must be summoned manually). Minibosses will spawn commonly. Perfect for fast-paced, intense gameplay!
	"Insanity Mode" = false
	#List IDs of any mobs you'd like to disable from the mod, separated by commas. You can find a mob's ID with the /summon command, but note that the arphex: part is not needed, and that this disables mobs completely from being spawned in any way, including existing mobs on world reload. Works on virtually all types of entities from the mod
	"Disable Specific Mobs" = ["mob_id", "mob_id", "mob_id (add as many as needed, e.g. spider_snatcher)"]
	#Enabled by default - controls whether non-boss hallucinations (like the spider ones) can spawn. Boss hallucinations are controlled by boss spawning.
	"Enable non-boss hallucination spawning" = true

[Difficulty]
	#By default, the stalker bosses have hundreds of health points. Choose true to decrease their maximum to just 60 health. Avoid decimal and negative numbers.
	"Boss easy-mode" = false
	#Can increase damage for most ArPhEx mob, miniboss, and boss attacks. Affects their ranged projectiles too. Default value is 0. Positive values will give that level of strength to all arphex mobs. Avoid decimal and negative numbers, upper limit is 256. Does not affect Tormentor fight significantly.
	"Extra Difficulty Control" = 0.0
	#Can lower damage for most ArPhEx mob, miniboss, and boss attacks. Affects their ranged projectiles too. Default value is 0. Positive values will give that level of weakness to all arphex mobs. Avoid decimal and negative numbers, upper limit is 256. Does not affect Tormentor fight significantly.
	"Lower Difficulty Control" = 0.0
	#Option to make the TORMENTOR weaker by lowering its max heath to any specific value. Default and maximum value is 1024.
	"Tormentor Max Health" = 1024.0
	#Value is in ticks. Since 20 ticks equate to a second, the default 25 ticks gives the Tormentor 1.25 seconds of immunity after each time it takes damage.
	"Tormentor Damage Speed Limit" = 20.0
	#With this mode enabled, all mobs from the mod become unable to target players for attack! For more peaceful gameplay, this is valuable. Full bosses such as the Tormentor and Voidlasher may not follow this setting entirely, so you may want to disable them if using this setting
	"Friendly Mode" = false
	#The Tormentor is an omnipresent eldritch god, so it follows you fast. However, you can change the percentage distance of teleportations to target here. 25% of the distance to target per teleportation by default, choose any percentage from 0-100% here
	"Tormentor Follow Speed" = 25.0

[Other]
	#When you join a world for the first time with ArPhEx installed, it shows a welcome message, informing you about the wiki and showing that the mod is active. Set to false to disable.
	"Welcome message" = true
	#Allow structure generations? Without them you will need to cheat to access the lower Crawling dimension layers or get ant colonies and termite-related items. Some tiny elements may still generate.
	"Structure generation toggle" = true
	#Keep enabled if you want to use the bonus rendering system for the Tormentor, featuring infinite render distance for the entity along with modifying fog distance accordingly, plus fog colour when nearby
	"Special Tormentor rendering" = true
	#The Tormented Wrath is an explosive post-Tormentor weapon that can shoot more and more powerful explosives the more times its user has killed the final Tormentor boss. You can limit the charge level here (default is 200, matching with the maximum amount of Tormentor kills that can be registered)
	"Limit Tormented Wrath Power" = 100.0
	#Disable to limit the staff's ability to walk through walls if it breaks something in your map or modpack
	"Allow Ethereal Staff wall bypassing" = true
	#To encourage players to build a den for their ant queens, the queens are required to be under a roof, or take damage otherwise. Set to false to disable the damage
	"Ant Queen outside damage" = true
	#Set to false to disable the Tormentor's cloud of particles. These can have a significant performance hit for some users.
	"Tormentor Particles" = true
	#Enable Tormentor's ability to add blurring and desaturation shaders when Tormenting
	"Tormentor Shaders" = true
	#The Tormentor can occasionally respond to chat messages that mention its name, using a random threatening line. There are 32 built-in messages. You can add your own below, one per line. Each custom entry you add reduces the chance of using a built-in line. If you list 32 or more custom messages, only your custom responses will ever be used.
	"Bonus Tormentor Chat Messages" = ["I am here, mortal", "Your torment is inevitable"]
	#When the tormentor responds to a chat message, it has a 50% chance to cooldown. This config option lets you choose how many seconds it would cooldown for
	"Tormentor Response Cooldown" = 2400.0
	#Set to false to disable mobs like locusts from breaking crops, and minibosses/bosses from breaking leaves. Does not affect tamed ant commands, or the Tormentor's attacks
	"ArPhEx Griefing" = true
	#Set to false to disable explosions from the final Tormentor boss' attacks - note that it only attacks if attacked first, and won't target players who died within the last minute, so its terrain damage can be localised to specific areas or avoided entirely with flight.
	"Tormentor Griefing" = true
	#Enables the Crawling Castle to generate on the world surface if enabled - otherwise generates underground
	"Crawling Castle Surface" = true

