#Chance to generate a random lock on every new chest during world generation. Set to 0 to disable
#在世界生成过程中，每个新箱子生成一个随机锁的概率。设置为0以禁用此功能。
#Range: 0.0 ~ 1.0
"Generation Chance" = 0.85
#Chance to randomly enchant a generated lock during world generation. Set to 0 to disable
#在世界生成过程中，随机附魔生成的锁的概率。设置为0以禁用此功能。
#Range: 0.0 ~ 1.0
"Generation Enchant Chance" = 0.4
#Blocks that can be locked during the world generation
#当世界生成时锁定的方块
"Lockable Generated Blocks" = ["minecraft:chest", "minecraft:barrel", "lootr:.*", "quark:.*_chest"]
#Items that can be generated as locks (must be instance of LockItem in code!)
#可以作为锁生成的物品（在代码中必须是 LockItem 的实例！）
"Generated Locks" = ["locks:wood_lock", "locks:iron_lock", "locks:steel_lock", "locks:gold_lock", "locks:diamond_lock"]
#WARNING: THE AMOUNT OF NUMBERS SHOULD BE EQUAL TO THE AMOUNT OF GENERATED LOCK ITEMS!!!
#The relative probability that the corresponding lock item will be generated on a chest. Higher number = higher chance to generate
#警告：数字的数量应与生成的锁数量相等！！！
#对应锁物品生成在箱子上的相对概率。数字越大，生成的机会越高。
"Generated Lock Chances" = [5, 4, 2, 3, 1]
#Randomize lock IDs and combinations when loading them from a structure file. Randomization works just like during world generation
#从结构文件加载锁ID和组合时进行随机化。随机化的方式与世界生成时相同。
"Randomize Loaded Locks" = true

